// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//y starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// フィボナッチ数列のn番目の数を求める, n>0
function searchFibonacci(n){
    if(n === 1){
        return 1;
    }else if(n === 2){
        return 2;
    }else{
        return searchFibonacci(n-1) + searchFibonacci(n-2);
    }
}

//test 
console.log(searchFibonacci(8)); // -> 34
console.log(searchFibonacci(2)); // -> 2

function sumEvenFibonacci(limit){
    let sum = 0;
    for(let i = 1; searchFibonacci(i) < limit; i++){
        if(searchFibonacci(i)%2 === 0){
            sum += searchFibonacci(i);
        }
    }
    return sum;
}

//test
console.log(sumEvenFibonacci(4)); // -> 2
console.log(sumEvenFibonacci(15)); // -> 10
console.log(sumEvenFibonacci(4000000)); // -> 4613732